version: '3.8'

x-db: &db
  platform: linux/x86_64
  image: mysql:8.0.29
  command:
    [
      "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_bin",
      "--sql-mode=TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY",
    ]
x-dbenv: &dbenv
  MYSQL_ROOT_PASSWORD: 123456
  MYSQL_USER: admin
  MYSQL_PASSWORD: 123456

services:
  jacee:
    image: nguyenchi2104/jacee_master:0.2
    restart: always
    ports:
      - 8000:8000

  appdb:
    <<: *db
    ports:
      - 13306:3306
    environment:
      <<: *dbenv
      MYSQL_DATABASE: jacee

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 16379:6379
    command: redis-server --requirepass cheesecute

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    links:
      - appdb
